### ISSUE TITLE
A similar project for file-system-less MCU

### ISSUE THREAD

**Issue by JiapengLi** [janjongboom/janpatch#12]
https://github.com/JiapengLi/mJPatch

~~mJPatch is inspired by JANPatch, the goal is to rewrite JANPatch and decouple the dependencies of file management APIs to make the library could work with MCU easily no mater it supports file system or not.~~

mJPatch is inspired by JANPatch, it is a pure C library. Which may helps those who like use C language to develop.

**Comment by janjongboom** [comment]
Hi @JiapengLi, great to see that you think it's useful. However, have you seen that you can use this on non-file system based devices as well? E.g. https://github.com/janjongboom/mbed-delta-update/blob/master/BDFile.h wraps around a very simple DataFlash flash chip without file system capabilities (used here: https://github.com/janjongboom/binary-diff-mbedos5/blob/xdot/src/main.cpp#L52).

**Comment by JiapengLi** [comment]
Great! Thank you for your hints. You did very excellent project. I need modify the description in case of misleading others.
