### ISSUE TITLE
How to generate hash file & patch file?

### ISSUE THREAD

**Issue by amin-nano-sys** [janjongboom/janpatch#19]
Hi sir!

Thanks for your nice work!

I want to use delta firmware update OTA for STM32l433 mcu but I do not know how to generate patch file & hash file for this purpose.
would you help me please?

best.

**Comment by janjongboom** [comment]
Hi, to generate the patch file just follow https://github.com/janjongboom/janpatch#generating-patch-files - how you then generate a hash or do the update is up to the update client in the firmware. I've written about it using Mbed's FlashIAP API (there's probably something similar in STM32 HAL) here https://os.mbed.com/blog/entry/firmware-updates-mbed-5-flashiap/
