### ISSUE TITLE
janpatch-cli.c causes "multiple definition of main"

### ISSUE THREAD

**Issue by amq** [janjongboom/janpatch#7]
How to reproduce:
1. Create a project with `janpatch.lib`
2. `mbed export -i gnuarmeclipse`
3. Build in [Eclipse](https://github.com/gnu-mcu-eclipse/org.eclipse.epp.packages/releases/)

Possible solutions:
- Move `janpatch-cli.c` to some demo project
- Move `janpatch-cli.c` to `TESTS/`

**Comment by janjongboom** [comment]
@amq So I've covered this by having an .mbedignore file present, which ignores the file when building with Mbed CLI. Apparently mbedignore is not respected by the gnuarmeclipse exporter. Made a bug report in mbed-os: https://github.com/ARMmbed/mbed-os/issues/6060

**Comment by amq** [comment]
Seems like a fix in mbed-os / mbed-cli is quite far away, could you use a workaround in the meantime?

**Comment by janjongboom** [comment]
Fixed in #8
